#!/bin/sh
# Generated by `praetor init`. Editing this file voids your warranty.

set -e

# Locate praetor binary
if command -v praetor >/dev/null 2>&1; then
    PRAETOR=praetor
elif [ -x ~/praetor-lsp/target/debug/praetor ]; then
    PRAETOR=~/praetor-lsp/target/debug/praetor
elif [ -x ./target/debug/praetor ]; then
    PRAETOR=./target/debug/praetor
else
    echo "praetor: not found on PATH or in ~/praetor-lsp/target/debug/"
    echo "Install with: cargo install --path ~/praetor-lsp"
    exit 1
fi

# Run validation — exits 1 if unproven WARNING/ERROR diagnostics exist
"$PRAETOR" validate --warn
exit $?
